USE SHOPEE
GO


------------------------------------------------------------------------------------
---index trên quan hệ PRODUCT, thuộc tính SHOP
DROP INDEX S_PD ON PRODUCT

SELECT  PRICE,O_AMOUNT
		FROM dbo.SHOP,dbo.PRODUCT ,dbo.CLASSIFICATION,dbo.ORDER_DETAIL
		WHERE SHOP_ID = SHOP
		AND PRODUCT_ID = PRODUCT
		AND GROUP_ID = O_GROUP
		AND OD_ORDER IN (SELECT S_ORDER
						FROM dbo.STATUS_INFO
						WHERE STATUS = 'S07'
						AND YEAR(S_MODIFIED_DATE) = 2019
						AND (SELECT MONTH(S_MODIFIED_DATE))= 6)
		AND SHOP = 'acc199'

CREATE INDEX S_PD ON PRODUCT(SHOP)

SELECT  PRICE,O_AMOUNT
		FROM dbo.SHOP,dbo.PRODUCT ,dbo.CLASSIFICATION,dbo.ORDER_DETAIL
		WHERE SHOP_ID = SHOP
		AND PRODUCT_ID = PRODUCT
		AND GROUP_ID = O_GROUP
		AND OD_ORDER IN (SELECT S_ORDER
						FROM dbo.STATUS_INFO
						WHERE STATUS = 'S07'
						AND YEAR(S_MODIFIED_DATE) = 2019
						AND (SELECT MONTH(S_MODIFIED_DATE))= 6)
		AND SHOP = 'acc199'

------------------------------------------------------------------------------------
---index trên quan hệ PRODUCT, thuộc tính CATEGORY

DROP INDEX PD_CG ON PRODUCT

SELECT DISTINCT PRODUCT_NAME, SHOP_NAME, AVERAGE_RATING, PRICE, GROUP_NAME
from CATEGORY, PRODUCT, SHOP, RATING, CLASSIFICATION 
where CATEGORY_NAME = N'Thời Trang Nam' and CATEGORY = CATEGORY_ID and SHOP = SHOP_ID and PRODUCT_ID = PRODUCT

CREATE INDEX PD_CG ON PRODUCT (CATEGORY) 
INCLUDE (SHOP, PRODUCT_NAME, AVERAGE_RATING) 

SELECT DISTINCT PRODUCT_NAME, SHOP_NAME, AVERAGE_RATING, PRICE, GROUP_NAME
from CATEGORY, PRODUCT, SHOP, RATING, CLASSIFICATION 
where CATEGORY_NAME = N'Thời Trang Nam' and CATEGORY = CATEGORY_ID and SHOP = SHOP_ID and PRODUCT_ID = PRODUCT

------------------------------------------------------------------------------------
---index trên quan hệ CLASSIFICATION, thuộc tính PRODUCT

DROP INDEX CSCF_PD ON CLASSIFICATION

SELECT DISTINCT PRODUCT_NAME, SHOP_NAME, AVERAGE_RATING, PRICE, GROUP_NAME
from CATEGORY, PRODUCT, SHOP, RATING, CLASSIFICATION 
where CATEGORY_NAME = N'Thời Trang Nam' and CATEGORY = CATEGORY_ID and SHOP = SHOP_ID and PRODUCT_ID = PRODUCT

CREATE INDEX CSCF_PD ON CLASSIFICATION (PRODUCT)
INCLUDE (GROUP_NAME, PRICE)

SELECT DISTINCT PRODUCT_NAME, SHOP_NAME, AVERAGE_RATING, PRICE, GROUP_NAME
from CATEGORY, PRODUCT, SHOP, RATING, CLASSIFICATION 
where CATEGORY_NAME = N'Chăm sóc thú cưng' and CATEGORY = CATEGORY_ID and SHOP = SHOP_ID and PRODUCT_ID = PRODUCT

SELECT * FROM CATEGORY

SELECT COUNT(CATEGORY)  FROM PRODUCT
GROUP BY (CATEGORY)

------------------------------------------------------------------------------------
---index trên quan hệ IMAGE, thuộc tính I_PRODUCT

DROP INDEX IM_PD ON IMAGE

SELECT DISTINCT PRODUCT_NAME, AVERAGE_RATING, PRICE, GROUP_NAME,  IMAGE_LINK
from CATEGORY, PRODUCT, IMAGE, RATING, CLASSIFICATION 
where CATEGORY_NAME = N'Thời Trang Nam' and CATEGORY = CATEGORY_ID and PRODUCT_ID= I_PRODUCT and PRODUCT_ID = PRODUCT

CREATE INDEX IM_PD ON IMAGE (I_PRODUCT)
INCLUDE (IMAGE_LINK)

SELECT DISTINCT PRODUCT_NAME, AVERAGE_RATING, PRICE, GROUP_NAME,  IMAGE_LINK
from CATEGORY, PRODUCT, IMAGE, RATING, CLASSIFICATION 
where CATEGORY_NAME = N'Thời Trang Nam' and CATEGORY = CATEGORY_ID and PRODUCT_ID= I_PRODUCT and PRODUCT_ID = PRODUCT

------------------------------------------------------------------------------------
---index trên quan hệ RATING, thuộc tính R_PRODUCT

DROP INDEX IDX_RATING_PD ON RATING

SELECT DISTINCT  P.PRODUCT_NAME, P.SHOP, P.PRODUCE_TYPE, P.INFORMATION, P.PREODER, P.PRODUCT_STATUS, P.AVERAGE_RATING, P.WEIGHT, C.CATEGORY_NAME, I.IMAGE_LINK, CL.GROUP_NAME, CL.INVENTORY_NUMBER, CL.PRICE, R.STAR_NUMBER, RL.CONTEND
		FROM PRODUCT P,CATEGORY C, IMAGE I, CLASSIFICATION CL, RATING R, REPLY RL
		WHERE P.PRODUCT_ID = 'prd5377'       
		AND P.CATEGORY = C.CATEGORY_ID
		AND P.PRODUCT_ID = I.I_PRODUCT
		AND P.PRODUCT_ID = CL.PRODUCT
		AND P.PRODUCT_ID = R.R_PRODUCT 
		AND R.RATING_ID = RL.RATING

CREATE INDEX IDX_RATING_PD ON RATING (R_PRODUCT)

SELECT DISTINCT  P.PRODUCT_NAME, P.SHOP, P.PRODUCE_TYPE, P.INFORMATION, P.PREODER, P.PRODUCT_STATUS, P.AVERAGE_RATING, P.WEIGHT, C.CATEGORY_NAME, CL.GROUP_NAME, CL.INVENTORY_NUMBER, CL.PRICE, R.STAR_NUMBER
		FROM PRODUCT P,CATEGORY C, CLASSIFICATION CL, RATING R
		WHERE P.PRODUCT_ID = 'prd5377'       
		AND P.CATEGORY = C.CATEGORY_ID
		AND P.PRODUCT_ID = CL.PRODUCT
		AND P.PRODUCT_ID = R.R_PRODUCT 



